// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace WeatherServiceML.Model
{
    public class ModelInput
    {
        [ColumnName("Label"), LoadColumn(0)]
        public string Label { get; set; }


        [ColumnName("Title"), LoadColumn(1)]
        public float Title { get; set; }


        [ColumnName("URL"), LoadColumn(2)]
        public float URL { get; set; }


        [ColumnName("ImageSource"), LoadColumn(3)]
        public string ImageSource { get; set; }


    }
}
